### PR TITLE
ffmpeg: map AYUV to vuyx

### PR DESCRIPTION
**Pull request by uartie**
Since:
 https://github.com/FFmpeg/FFmpeg/commit/caf26a8a126d

### CODE REVIEW

**Comment by uartie** [comment]
@xhaihao can you update ffmpeg-qsv in cartwheel, too, to use vuyx instead of vuya?

**Review by FocusLuo — APPROVED** [review]
LGTM

**Comment by xhaihao** [comment]
@uartie  I updated ffmpeg-qsv to use vuyx instead of vuya, see https://github.com/intel-media-ci/cartwheel-ffmpeg/pull/177, and https://github.com/Intel-Media-SDK/MediaSDK/pull/2768 is required.

**Comment by xhaihao** [comment]
@uartie  https://github.com/intel-media-ci/ffmpeg/pull/576 is PR for FFmpeg mainline.

**Pull request merged**
