### PR TITLE
Added Y412 format (12bit YUV444 ) support for HEVC-12 main444 decode

### PR DESCRIPTION
**Pull request by FocusLuo**
Added 12bit YUV444 support for HEVC-12 main444 decode and gst-msdk implementation

### CODE REVIEW

**Comment by FocusLuo** [comment]
root@8f8578038cd1:/home/focus/workspace_focus/vaapi-fits# ./vaapi-fits run test/self/formats.py --pl=TGL -k fmt=Y412
27 tests collected
test/self/formats.py ...........................  PASS
======================================= Session ended. 27 successful, 0 skipped, 0 failed, 0 erroneous. Total duration: 00:00:02 ========================================
root@8f8578038cd1:/home/focus/workspace_focus/vaapi-fits#

**Comment by uartie** [comment]
Please submit a patch to https://github.com/intel-media-ci/gst-checksumsink/blob/master/gstchecksumsink.c to add support for `Y412_LE` format.  Also, it appears `P012_LE` is missing from checksumsink2, too.

**Comment by FocusLuo** [comment]
The Y412_LE and P012_LE were supported in https://github.com/xhaihao/gst-checksumsink.
@uartie @zhoujd do you happen to know what's the difference between the https://github.com/intel-media-ci/gst-checksumsink and https://github.com/xhaihao/gst-checksumsink
I remembered that the media-ci is using the mirror of https://github.com/xhaihao/gst-checksumsink for gst-checksumsink

**Comment by uartie** [comment]
The media ci uses https://github.com/intel-media-ci/gst-checksumsink/blob/master/gstchecksumsink.c

**Comment by uartie** [comment]
In theory, the [intel-media-ci](https://github.com/intel-media-ci/gst-checksumsink) gst-checksumsink fork will allow us to have multiple "maintainers" from our team to manage pull-requests/changes to support CI.  Whereas, [xhaihao](https://github.com/xhaihao/gst-checksumsink) and [ceyusa](https://github.com/ceyusa/gst-checksumsink) forks are limited to a single maintainer.  If either one of those maintainers are unavailable (e.g. vacation), then we shouldn't have to wait for them to respond.

Unfortunately, it looks like gst-checksumsink for [intel-media-ci](https://github.com/intel-media-ci/gst-checksumsink) is forked from [xhaihao](https://github.com/xhaihao/gst-checksumsink) .  And [xhaihao](https://github.com/xhaihao/gst-checksumsink) is forked from [ceyusa](https://github.com/ceyusa/gst-checksumsink).  Instead, I think  [intel-media-ci](https://github.com/intel-media-ci/gst-checksumsink) should be forked from [ceyusa](https://github.com/ceyusa/gst-checksumsink).  We need to fix that and apply all of [xhaihao](https://github.com/xhaihao/gst-checksumsink) extra patches to [intel-media-ci](https://github.com/intel-media-ci/gst-checksumsink).  And all future patches from us should be submitted to [intel-media-ci](https://github.com/intel-media-ci/gst-checksumsink), including patches by @xhaihao

**Comment by FocusLuo** [comment]
I see, thanks Artie, I rebased Haihao's patch into intel-media-ci and am trying to some sanity testing against intel-media-ci gst-checksumsink. If no issue found, then will submit the rebased intel-media-ci commits into the intel-media-ci master

**Comment by uartie** [comment]
I have already pushed @xhaihao patches to intel-media-ci fork and changed it to be a fork from ceyusa

**Comment by FocusLuo** [comment]
Good, thanks @uartie

**Pull request merged**
