### PR TITLE
gst/transcode: add qtmux for x264enc

### PR DESCRIPTION
**Pull request by yefengxx**
Fix the issue that files encoded by gst-x264enc cannot be decoded.

Signed-off-by: Yefeng Xu <yefengx.xu@intel.com>

### CODE REVIEW

**Comment by yefengxx** [comment]
@uartie @FocusLuo can you review this for me?

**Comment by FocusLuo** [comment]
@yefengxx did you do any testing? can you help also supply some test result comments here?

**Comment by uartie** [comment]
#318 conflicts with this change

**Comment by uartie** [comment]
Also, please rebase patchset with latest master

**Comment by uartie** [comment]
close.  please address reviews and reopen if you feel this is still needed

**Pull request closed without merging**
