### PR TITLE
ffmpeg/gstreamer: use correct test spec in csc/r2r

### PR DESCRIPTION
**Pull request by Hangjie22Coder**
This change references the number of the previous PR: 582

### CODE REVIEW

**Review by uartie — CHANGES_REQUESTED** [review]
Ugh, I missed this in PR review.  Glad you've caught this now.  Thanks for the fix.

Please improve your commit messages.  The title is too long and generic.  Explain "what" you are fixing.  For example, _"ffmpeg-vaapi/csc: use correct test spec in R2R"_.  Also, the reference to bad commit that you are fixing only needs to be in the message body, not title.

**Comment by uartie** [comment]
...also, please make sure you separate the title and body by an empty line in the commit message.  Otherwise, `git log --oneline` will merge them together as a long title.

**Comment by uartie** [comment]
FYI, gst-va/csc was fixed in https://github.com/intel/vaapi-fits/pull/590... please rebase.

**Comment by Hangjie22Coder** [comment]
Thanks for the review, updated.

**Pull request merged**
