### PR TITLE
Removed the P410 format support

### PR DESCRIPTION
**Pull request by FocusLuo**
P410 in vaapi-fits are implemented incorrectly as
3 planes (Y plane + U plane + V plane). And the
ffmpeg and gstreamer do not have appropriate formats
to handle unofficial P410 formats

Y410 have better support across the media SW stacks
(drivers & middleware), which had been merged

Signed-off-by: Luo Focus <focus.luo@intel.com>

### CODE REVIEW

**Comment by FocusLuo** [comment]
Test result after removed the P410 format
root@media_libva_icl2:/home/focus/workspace_focus/to_remove_P210_P410/vaapi-fits# ./vaapi-fits run test/self/formats.py --pl ICL
306 tests collected
test/self/formats.py ..................................................................................................................................................................................................................................................................................................................  PASS
======================================= Session ended. 306 successful, 0 skipped, 0 failed, 0 erroneous. Total duration: 00:01:56 =======================================

**Comment by zhoujd** [comment]
It looks like there are conflicts in the patches, please resolve it.

**Comment by FocusLuo** [comment]
> It looks like there are conflicts in the patches, please resolve it.

Ok, let me update soon, just focused on sanity test suites dev in the last week

**Comment by zhoujd** [comment]
I am merging this patch, thanks.

**Pull request merged**
