### PR TITLE
lib/platform: support avc enc LP on SKL

### PR DESCRIPTION
**Pull request by wangzj0601**
it should support h264 enc lowpower mode on skl.

### CODE REVIEW

**Comment by uartie** [comment]
It looks like i965 supports it according to the code [here](https://github.com/intel/intel-vaapi-driver/blob/10507d3fb6c678d005ef6ed241e24a0d119ca3ba/src/i965_device_info.c#L375).

But, according to the iHD [README](https://github.com/intel/media-driver#hw-media-features), AVC VDENC is not supported on SKL.  Do you have evidence that suggests it is, otherwise?

**Comment by wangzj0601** [comment]
from my skl unit, I found it support h264 enc lp mode on iHD driver.
      **VAProfileH264Main               : VAEntrypointEncSliceLP**
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointFEI
      **VAProfileH264High               : VAEntrypointEncSliceLP**
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointFEI
      **VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP**

**Comment by uartie** [comment]
Did you try to run AVC vdenc cases on SKL with iHD?  Do they work?  I'm curious why iHD would document it as unsupported (maybe it's not ready?).

**Comment by wangzj0601** [comment]
I have run avc cqp lp tests, they work well.

**Comment by uartie** [comment]
OK, thanks.  LGTM.  We can check CI after it runs them, too.

**Comment by wangzj0601** [comment]
you can also refer to this https://github.com/intel/media-driver/issues/465

**Pull request merged**
