### PR TITLE
[ffmpeg-vaapi] Address issues introduced by a prior merge.

### PR DESCRIPTION
**Pull request by Hangjie22Coder**
[ffmpeg-vaapi] updated FFMPEG-VAAPI encoding AV1 cmd line. 

ffmpeg don't have option about `-icq`

### CODE REVIEW

**Comment by Hangjie22Coder** [comment]
Address issues introduced by a prior merge: https://github.com/intel/vaapi-fits/pull/615

**Comment by Hangjie22Coder** [comment]
Hi @Bin-CI Can you help me review it?

**Comment by Hangjie22Coder** [comment]
Hi @uartie can you review this for me?

**Review by uartie — APPROVED** [review]

**Comment by uartie** [comment]
test failures not caused by this commit.  fixed in https://github.com/intel/vaapi-fits/pull/621

**Pull request merged**
