### PR TITLE
gst-msdk: added max_frame_size for avc enc

### PR DESCRIPTION
**Pull request by yefengxx**
added max_frame_size for gst-msdk avc enc

Signed-off-by: Xu Yefeng <yefengx.xu@intel.com>

### CODE REVIEW

**Comment by yefengxx** [comment]
It depends on https://github.com/intel/vaapi-fits/pull/395

**Comment by yefengxx** [comment]
@uartie @FocusLuo can you review this for me?

**Comment by uartie** [comment]
Please combine #395, #396 and #397 patches into the same PR.  Otherwise, these will not pass the pre-check.

**Comment by uartie** [comment]
NOTE: a PR can have multiple commits when they are related/dependent to one another.

**Comment by yefengxx** [comment]
A new PR is submitted in https://github.com/intel/vaapi-fits/pull/398

**Pull request closed without merging**
