### PR TITLE
gst-msdk/vpp: add crop test

### PR DESCRIPTION
**Pull request by uartie**
Depends on https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/issues/1097

Signed-off-by: U. Artie Eoff <ullysses.a.eoff@intel.com>

### CODE REVIEW

**Comment by uartie** [comment]
> This patch supports python2 or python3 ?

vaapi-fits has not been ported to python 3, yet.  That is your task.

**Comment by uartie** [comment]
> > This patch supports python2 or python3 ?
> 
> vaapi-fits has not been ported to python 3, yet. That is your task.

either way, this patch should work with both versions of python

**Comment by zhoujd** [comment]
well, all the patches with python3 and python2  compatibility will be good .

**Comment by zhoujd** [comment]
It looks good to me. quick checked on local CI, will apply the patch if no objection

**Comment by uartie** [comment]
> It looks good to me. quick checked on local CI, will apply the patch if no objection

Please don't merge until gst-plugins-bad crop patch is merged (see "Depends" link above).

**Pull request merged**
