### PR TITLE
parameters: support DI method or rate variation

### PR DESCRIPTION
**Pull request by uartie**
Allow user config to set either method or rate
and variate the other for deinterlace tests.

Examples for previous accepted syntax:
```
modes = [dict(method = "bob", rate = "frame"),] # "bob" method with "frame" rate

modes = [
  dict(method = "bob", rate = "frame"),
  dict(method = "weave", rate = "field"),
] # "bob" method with "frame" rate AND "weave" method with "field" rate.
```

Examples for additional syntax provided by this patch :
```
modes = [dict(rate = "frame"),] # all default methods with "frame" rate.

modes = [dict(method = "bob"),] # "bob" method with all default rates.
```

### CODE REVIEW

**Comment by FocusLuo** [comment]
let me to try this patch later, it seems better solution for all middleware

**Comment by FocusLuo** [comment]
@uartie I tried your patch,  there are issues found:
the dynamic mode or rate set in "config/default/vpp.smoke" can not be successful (only define v.setdefault("rate", ["frame"]) in config file)

 I added a print log "print("Hello Focus: method=, rate= ", method, rate)" in gen_vpp_deinterlace_variants
./smoke run test/ffmpeg-vaapi/vpp/deinterlace.py --pl CFL
Hello Focus: method=, rate=  bob field
Hello Focus: method=, rate=  bob frame
Hello Focus: method=, rate=  weave field
Hello Focus: method=, rate=  weave frame
Hello Focus: method=, rate=  motion-adaptive field
Hello Focus: method=, rate=  motion-adaptive frame
Hello Focus: method=, rate=  motion-compensated field
Hello Focus: method=, rate=  motion-compensated frame
Hello Focus: method=, rate=  bob field
Hello Focus: method=, rate=  bob frame
Hello Focus: method=, rate=  weave field
Hello Focus: method=, rate=  weave frame
Hello Focus: method=, rate=  motion-adaptive field
Hello Focus: method=, rate=  motion-adaptive frame
Hello Focus: method=, rate=  motion-compensated field
Hello Focus: method=, rate=  motion-compensated frame
Hello Focus: method=, rate=  bob field
Hello Focus: method=, rate=  bob frame
Hello Focus: method=, rate=  weave field
Hello Focus: method=, rate=  weave frame
Hello Focus: method=, rate=  motion-adaptive field
Hello Focus: method=, rate=  motion-adaptive frame
Hello Focus: method=, rate=  motion-compensated field
Hello Focus: method=, rate=  motion-compensated frame
Hello Focus: method=, rate=  bob field
Hello Focus: method=, rate=  bob frame
Hello Focus: method=, rate=  weave field
Hello Focus: method=, rate=  weave frame
Hello Focus: method=, rate=  motion-adaptive field
Hello Focus: method=, rate=  motion-adaptive frame
Hello Focus: method=, rate=  motion-compensated field
Hello Focus: method=, rate=  motion-compensated frame

def gen_vpp_deinterlace_variants(spec, modes):
  for case, params in spec.items():
    seen = set()
    variants = params.get("modes", modes)

    for variant in variants:
      method = variant.get("method", None)
      rate = variant.get("rate", None)

      print("Hello Focus: method=, rate= ", method, rate)
      if method is None: # method is variant, rate is fixed
        assert rate is not None, "user config must specify method and/or rate"
        matched = filter(lambda m: m["rate"] == rate, modes)
      elif rate is None: # rate is variant, method is fixed
        assert method is not None, "user config must specify method and/or rate"
        matched = filter(lambda m: m["method"] == method, modes)
      else: # rate and method are fixed
        matched = [variant]

      for match in matched:
        hashkey = tuple(sorted(match.values()))
        if hashkey not in seen:
          yield [case, match["method"], match["rate"]]
          seen.add(hashkey)

**Comment by FocusLuo** [comment]
Step1 The vpp config set (vaapi-fits-smoke/full/sanity)--> Step 2, ffmpeg-vaapi (vaapi-fits implement, test/ffmpeg-vaapi/vpp/deinterlace.py)--> Step 3, parameter library (gen_vpp_deinterlace_variants)
In the step 2, take the "class avc" for example:
the slash.parametrize will call the default fixed parameter _default_methods_" and "_default_modes_" (defined in test/ffmpeg-vaapi/vpp/deinterlace.py ") to set parameter in Step 3
So maybe we still need to deal the parameters in step 2

The slash.parametrize(
    *gen_vpp_deinterlace_parameters(
      spec_mpeg2, DeinterlaceTest._default_modes_))

**Comment by uartie** [comment]
In you config, you need to use `v.setdefault("modes", [dict(rate = "frame")])`

**Comment by uartie** [comment]
`modes` should be a list of dict.  Each dict is a _mode_ that should contain either the "method" or "rate" key/value entries (or both).

I already provided some examples in https://github.com/intel/vaapi-fits/pull/196#discussion_r430599029

**Comment by uartie** [comment]
I have updated the description to include some syntax examples.

**Comment by uartie** [comment]
I have updated the code with documentation and better variable naming... hopefully that will make it more intuitive to understand how user config/spec needs to be defined.

**Pull request merged**
